---
- name: Creating list of users for {{ansible_hostname}}
  hosts: ubuntu
  vars:
   users_var:
    - name: trie
      group: sudo
    - name: tree
      group: users
  tasks:
   - name: creating users
     user:
      name: "{{item.name}}"
      group: "{{item.group}}"
     loop: "{{users_var}}"
...  

