---
- name: Creating user ids and copying files to home directories
  hosts: all
  become: yes
  tasks:
   - name: Creating users on all manage nodes
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: Creating files into home directories
     file:
      name: "{{d}}"
      state: "{{e}}"
...
