
---
- name: Testing local execution
  hosts: rhel
  become: yes
  gather_facts: no
  vars:
   action: directory
  tasks:
   - name: renaming the file
     command: "mv ukdc2-2c-config.localpaytd.local.pfx psc_console.pfx"
     delegate_to: localhost
     run_once: yes
     tags:
      - local
   - name: running delegating command       
     file:
      path: /tmp/{{inventory_hostname}}
      state: "{{action}}"
      mode: 0755
     run_once: yes
     delegate_to: localhost
   - name: create folders in localhost based upon the env
     file:
      path: /tmp/2c
      state: directory
     delegate_to: localhost
     when: " inventory_hostname | regex_search('.*2c.*', ignorecase=True)"
   - name: Create folder with vaultpsd
     file:
      path: /tmp/{{testpsc}}.{{env}}
      state: touch
     delegate_to: localhost
     tags:
      - vault
   - name: Testing vaults
     command: "{{item}}"
     with_items:
      - echo "Testing pscadminpsd {{testpsc}}"
     delegate_to: localhost
     tags:
      - vault 
   - name: Running this on {{inventory_hostname}}
     file:
      path: /tmp/{{testpsc}}.{{env}}
      state: touch
     when: "inventory_hostname == mngr_node"
     tags:
      - vault

