
---
- name: Checking the foldrt status for multiple servers
  hosts: ubuntu
  become: yes
  vars:
   server:
    - 192.168.55.82
    - 192.168.55.48
  tasks:
   - name: Checking status of folder in {{inventory_hostname}}
     command: ls /tmp/copy/
     ignore_errors: yes
     register: st
     tags:
      - reg
   - name: Create folder if it's not existed
     copy:
      src: server.xml
      dest: /tmp/copy/
     when: ( item is succeeded ) and ( inventory_hostname in server)
     with_items:
      - "{{st}}"
   - name: output the results
     debug:
      var: st
     tags:
      - reg
