
---
- name: Install multiple packages
  hosts: all
  tasks:
   - name: Download terraform from online
     get_url:
      url: https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_386.zip
      dest: /tmp/terraform.zip
   - name: Checking download status
     command: 'ls /tmp/terraform.zip'
     register: stat
   - name: Display the status
     debug:
      var: stat
   - name: create file in home directory
     file:
      path: ~/terraform
      state: directory
     register: dir
     ansible_user: osboxes
   - name: Display the status
     debug:
      var: dir
   - name: Unzip the {{stat.stdout}} file
     unarchive:
      src: /tmp/terraform.zip #"{{stat.stdout}}"
      dest: ~/terraform/
      remote_src: yes
      remote_user: osboxes
